name: Run status check and show log

runs:
  using: "composite"
  steps:
    - name: Run status check
      run: ${{ github.action_path }}/run
      shell: bash
    - name: Commit and push log.csv to log branch
      uses: stefanzweifel/git-auto-commit-action@v6
      if: always()
      with:
        file_pattern: 'log.csv'
        branch: 'log'
        commit_message: 'Update status log'
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        push_options: '--force'