name: Run status check and show log

runs:
  using: "composite"
  steps:
    - name: Run status check
      run: |
        #!/bin/bash
        set -e

        # Create curlrc config file
        cat > curlrc << 'EOF'
        --retry 5
        --retry-delay 5
        --retry-all-errors
        --fail
        --parallel
        --silent
        --output /dev/null
        --expand-write-out "%output{>>log.csv}{{id}},{{date}},%{http_code}\n"
        EOF

        if [ ! -f status.cfg ]; then
          echo "No config found"
          exit 0
        fi

        cmd=""
        url_count=0
        while IFS= read -r line || [[ -n $line ]]; do
          [[ -z $line || $line == \#* ]] && continue
          # Read first two fields: id and url
          read -r id url <<< "$line"
          [[ -z $id || -z $url ]] && continue
          # Extract everything after the URL as additional curl parameters
          rest="${line#*$url}"
          rest="${rest# }"  # Remove leading space if present
          url_count=$((url_count + 1))
          new_cmd="--variable id=${id} --config curlrc ${url}"
          [[ -n $rest ]] && new_cmd="$new_cmd $rest"
          if [[ -n $cmd ]]; then new_cmd="--next $new_cmd"; fi
          cmd="$cmd $new_cmd"
        done < status.cfg

        curl_exit_code=0
        if [[ -n $cmd ]]; then
          curl --variable date="$(date '+%Y-%m-%d %H:%M')" $cmd || curl_exit_code=$?
        fi

        if [[ -f log.csv ]]; then
          lines_to_keep=$((url_count * 8640))
          tail -n "$lines_to_keep" log.csv > log.csv.tmp && mv log.csv.tmp log.csv
        fi

        exit $curl_exit_code
      shell: bash
    - name: Commit and push log.csv to log branch
      uses: stefanzweifel/git-auto-commit-action@v5
      if: always()
      with:
        file_pattern: 'log.csv'
        commit_message: 'Update status log'
        branch: 'log'
        create_branch: true
