name: Run status check and show log

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Set git identity
      run: |
        name="github-actions[bot]"
        email="41898282+github-actions[bot]@users.noreply.github.com"
        echo "GIT_AUTHOR_NAME=$name" >> $GITHUB_ENV
        echo "GIT_AUTHOR_EMAIL=$email" >> $GITHUB_ENV
        echo "GIT_COMMITTER_NAME=$name" >> $GITHUB_ENV
        echo "GIT_COMMITTER_EMAIL=$email" >> $GITHUB_ENV
      shell: bash
    - name: Run status check
      run: ${{ github.action_path }}/run
      shell: bash
    - name: Commit and push log.csv to log branch
      uses: stefanzweifel/git-auto-commit-action@v7
      if: always()
      with:
        file_pattern: 'log.csv'
        branch: 'log'
        create_branch: true
        commit_message: 'Update status log'
        commit_author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
        push_options: '--force'