name: Service Status Monitoring

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - 'master'
  workflow_dispatch:

concurrency:
  group: status-githack
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run status check and commit logs
        uses: neoascetic/status.githack.com@action
